language: node_js
node_js:
  - "7.9.0"
script:
  - npm run bootstrap && npm run test && npm run build
cache:
  yarn: true
  directories:
    - node_modules
after_success: npm run codecov
deploy:
  provider: npm
  skip_cleanup: true
  email: "laheen@gmail.com"
  api_key: $NPM_KEY
  on:
    tags: true
