language: node_js
node_js:
  - '8.9'
script:
  - yarn test
  - yarn build
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - node_modules
after_success: yarn codecov
deploy:
  provider: script
  script: touch ~/.npmrc && echo "//registry.npmjs.org/:_authToken=${NPM_KEY}" >> ~/.npmrc && yarn push-to-npm
  skip_cleanup: true
  on:
    tags: true
