language: node_js
node_js:
  - "8.6.0"
script:
  - npm run bootstrap
  - npm test
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - node_modules
after_success: npm run codecov
deploy:
  provider: script
  script: touch ~/.npmrc && echo "//registry.npmjs.org/:_authToken=${NPM_KEY}" >> ~/.npmrc && npm run publish
  skip_cleanup: true
  on:
    tags: true
